# languageCode = "en"
# languageName = "English"
# weight = 1
title = "Pietro's Tavern"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "images/logo.webp"
secondaryLogo = "images/logo.webp"
description = "Welcome to Pietro's Tavern, a virtual haven where ideas set sail and stories flow as freely as the rum. Here, you’ll find a treasure trove of intriguing content, from thought-provoking insights on philosophy, technology, and literature to delicious food and cocktail recipes inspired by the sea. Whether you’re here to discover a new idea, indulge in a great story, or enjoy a perfectly crafted drink, Pietro’s Tavern offers a welcoming space for curious minds to explore, learn, and savor life’s simple pleasures. Come aboard, pull up a seat, and let the adventure begin!"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Pietro's Tavern"
image = "images/logo.webp"
headline = "Where Ideas Set Sail, Tales Flow Freely, and Every Sip Tells a Story."
bio = "I'm a Computer Science student at Politecnico di Milano in Italy. Join me as I share my favourite and most interesting programming projects, written in C, Python and Rust."
links = [
  { email = "mailto:pietro_agnoli@proton.me" },
  #     { link = "https://link-to-some-website.com/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/TheCaptainCraken" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { keybase = "https://keybase.io/username" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  #     { linkedin = "https://linkedin.com/in/username" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  #     { telegram = "https://t.me/username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  #     { youtube = "https://youtube.com/username" },
  #     { ko-fi = "https://ko-fi.com/username" },
]
