# netlify.toml

[build]
command = "hugo mod get -u && hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.139.3"
TZ = "UTC+1"             # Set to preferred timezone
